---
title: "FRENCH OPEN 2019 (MEN'S SINGLES)"
output: 
  flexdashboard::flex_dashboard:
    source_code: https://github.com/SeanRichterWalsh/R_Workshops/blob/master/Flexdashboard_20191022/frenchopen_2019.csv
    orientation: rows
    theme: flatly
    vertical_layout: fill
---

<meta http-equiv="X-UA-Compatible" content="IE=edge">

<style>                     
.navbar {
  background-color:#C23B22;
  border-color:black;
}
.navbar-brand {
color:white!important;
}
.dygraph-axis-label {
  font-size: 11px;
}
</style> 


Overview
====================

```{r setup, include = FALSE}
# Load up libraries (many of these are loaded as part of the tidyverse suite)
library(dplyr)
library(tidyr)
library(forcats)
library(ggplot2)
library(plotly)
library(scales)
library(DT)
library(flexdashboard)

# Read in our tidied French Open 2019 data 
# The dashboard will be rendered in the directory of the .Rmd file by default
fo_data <- read.csv("/home/swalsh/frenchopen_2019.csv",
                    stringsAsFactors = FALSE)

fo_data$Date <- as.Date(fo_data$Date, 
                        format = "%Y-%m-%d") # We could have stored our cleaned data as .xlsx and used readxl

## Sources of information:
# https://www.rolandgarros.com/en-us/article/2019-numbers-record-
# https://www.schemecolor.com/french-open-tennis-court.php
# https://www.atptour.com/en/tournaments/roland-garros/520/overview
# https://www.rolandgarros.com/en-us/article/roland-garros-2019-new-prize-money-tournament-revealed
# https://rmarkdown.rstudio.com/flexdashboard/examples.html
# https://plot.ly/r/
# https://rstudio.github.io/DT/
```

Row
--------------------------------------

### ATP Points 

```{r atp points}
# Grand Slam winners get a whopping 2,000 ATP ranking points
slam_pts <- 2000

valueBox(comma(slam_pts),
         color = "#E3783B",
         icon = "fa-chart-line")
```

### Winner's Prize Money

```{r prize money}
# Prize money for the winner of the men's singles draw
prize_money <- 2300000

valueBox(comma(prize_money),
         color = "#E3783B",
         icon = "fa-euro-sign")
```

### Players

```{r n players}
# Total number of players in the men's singles draw
total_players <- 128

valueBox(total_players,
         color = "#E3783B",
         icon = "fa-user-friends")
```

Row
--------------------------------------

### **Video Views** 

```{r video views}
# Video views during the entire 2019 tournament (so not strictly limited to the men's singles draw)
gauge(121000000, 
      min = 0, 
      max = 150000000, 
      label = paste("vs. Target:", "-29M"), 
      gaugeSectors(success = c(120000000, 150000000), 
                   warning = c(100000000, 119999999), 
                   danger = c(0, 99999999),
                   colors = c("#6EAA39", "#FFA500", "#B70030")))
```

### **Fastest Serve**

```{r fastest serve}
# Fastest serve speed in the competition (M. Copil)
gauge(139, 
      symbol = "mph",
      min = 0, 
      max = 163.7, # Versus world record (S. Groth in 2012)
      label = paste("vs. WR"), 
      gaugeSectors(success = c(163.7, 200), 
                   warning = c(130, 163.6), 
                   danger = c(0, 129),
                   colors = c("#6EAA39", "#FFA500", "#B70030")))
```

Row 
--------------------------------------

### **Most Frequent Set Score**

```{r most frequent set score}
# Better to use html widgets with flexdashboard than static ggplot2 plots as the widgets will intelligently resize without specification
# What was the most frequent set score in the men's singles competition?
mfss <- fo_data %>% 
  select(1, 16:20) %>%
  filter(!is.na(Set4_Score),
         !is.na(Set5_Score)) %>%
  pivot_longer(c(Set1_Score, # Nice gather() alternative/improvement
                 Set2_Score,
                 Set3_Score,
                 Set4_Score,
                 Set5_Score),
               names_to = "Set",
               values_to = "Score") %>%
  ggplot(aes(x = fct_infreq(Score))) + # Nice little ordering trick using forcats!
  geom_bar(fill =  "#C23B22") +
  xlab("Set score") +
  ylab("Total") +
  theme(panel.background = element_rect(fill = "#F1F3F4"))

ggplotly(mfss,
         tooltip = "count") %>%
  config(displayModeBar = FALSE)
```   
 
### **ATP Points and Ranking** 

```{r points and ranking relationship}
# Plot the relationship between ATP ranking and ATP points before the competition
pr_rel <- fo_data %>%
  ggplot(aes(x = WPts, # Just sample winner ATP points
             y = WRank)) + # Just sample winner ATP ranking
  geom_line(size = 0.25) +
  xlab("ATP points") +
  ylab("ATP ranking") +
  scale_y_continuous(breaks = seq(0, 500, 10)) +
  geom_hline(yintercept = 10,
             colour = "#C23B22",
             linetype = "dashed") +
  theme(panel.background = element_rect(fill = "#F1F3F4")) 

ggplotly(pr_rel,
         tooltip = c("WPts", "WRank")) %>%
  config(displayModeBar = FALSE) 
```

Data
====================

### **French Open 2019 Men's Singles Data**

```{r source data}
# Source data for the 2019 French Open men's singles competition
fo_data %>%
  select(2:11, # Rearrange the column order for more intuitive viewing
         Wsets, 
         Lsets, 
         Set1_Score, 
         Set2_Score, 
         Set3_Score, 
         Set4_Score, 
         Set5_Score,
         WRank,
         LRank,
         Comment) %>%
  datatable(rownames = FALSE, # The data table can be tweaked in many ways (alignment, style, etc.)
            extensions = "Buttons",
            options = list(pageLength = 20,
                           dom = "Bfrtip",
                           buttons = c("csv", "excel"))) 
```








